import {
  Parcel,
  Building,
  Floor,
  Flat,
  ValidationResult,
  DigiLockerIntegration,
  BankKycIntegration,
  SearchResult,
  DashboardKPIs,
  SurveyRecord,
} from '../types';

export const INITIAL_PARCELS: Parcel[] = [
  {
    id: 'parcel-kp2-0442',
    name: 'Knowledge Park II — Institutional Sector 3',
    ulpin: 'UP-GNB-KP2-0442',
    area: 14850,
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    zone: 'Zone 04 (Greater Noida Expressway Corridors)',
    classification: 'Institutional & Tech R&D Cluster',
    confidence: 94,
    coordinates: {
      lat: 28.4682,
      lng: 77.5042,
    },
    boundaryGeoJson: {
      type: 'Polygon',
      coordinates: [
        [
          [77.5035, 28.4675],
          [77.5050, 28.4678],
          [77.5048, 28.4690],
          [77.5032, 28.4687],
          [77.5035, 28.4675],
        ],
      ],
    },
    buildingCount: 3,
    lastVerified: '2026-03-15T09:30:00Z',
    verificationLayers: {
      satellite: 96,
      drone: 98,
      lidar: 92,
      sanctionPlan: 90,
    },
    status: 'VERIFIED',
  },
  {
    id: 'parcel-ecity-108',
    name: 'Electronic City Phase 1 — Sub-division 12',
    ulpin: 'KA-BLR-EC1-1088',
    area: 21400,
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    zone: 'Southern Tech Belt — Hosur Radial',
    classification: 'Commercial Tech Infrastructure',
    confidence: 91,
    coordinates: {
      lat: 12.8452,
      lng: 77.6602,
    },
    buildingCount: 4,
    lastVerified: '2026-02-28T14:15:00Z',
    verificationLayers: {
      satellite: 92,
      drone: 94,
      lidar: 89,
      sanctionPlan: 89,
    },
    status: 'VERIFIED',
  },
  {
    id: 'parcel-gift-0901',
    name: 'GIFT City DTA Commercial Zone — Block C',
    ulpin: 'GJ-GND-GFT-0901',
    area: 18900,
    state: 'Gujarat',
    district: 'Gandhinagar',
    zone: 'International Financial Services Centre (IFSC)',
    classification: 'High-Rise Commercial High Density',
    confidence: 97,
    coordinates: {
      lat: 23.1610,
      lng: 72.6841,
    },
    buildingCount: 2,
    lastVerified: '2026-03-10T11:00:00Z',
    verificationLayers: {
      satellite: 98,
      drone: 99,
      lidar: 96,
      sanctionPlan: 95,
    },
    status: 'VERIFIED',
  },
  {
    id: 'parcel-cyb-0412',
    name: 'Cyber City Sector 25A — Parcel 412',
    ulpin: 'HR-GGN-CYB-0412',
    area: 12200,
    state: 'Haryana',
    district: 'Gurugram',
    zone: 'Transit Oriented Development Corridor',
    classification: 'Mixed Commercial Enterprise',
    confidence: 89,
    coordinates: {
      lat: 28.4950,
      lng: 77.0892,
    },
    buildingCount: 2,
    lastVerified: '2026-01-20T16:45:00Z',
    verificationLayers: {
      satellite: 90,
      drone: 88,
      lidar: 87,
      sanctionPlan: 91,
    },
    status: 'UNDER_SURVEY',
  },
];

export const INITIAL_BUILDINGS: Building[] = [
  {
    id: 'bldg-01',
    parcelId: 'parcel-kp2-0442',
    name: 'Aryabhata Innovation Tower (Building 01)',
    code: 'BUILDING 01',
    height: 48,
    area: 18200,
    floorsCount: 10,
    buildingType: 'R&D / Commercial Multi-Tenant',
    ulpin: 'BASE-V01-B01-CX',
    position: [0, 0, 0],
    dimensions: [18, 48, 14],
    status: 'ACTIVE',
  },
  {
    id: 'bldg-02',
    parcelId: 'parcel-kp2-0442',
    name: 'Brahmagupta Computing Wing (Building 02)',
    code: 'BUILDING 02',
    height: 32,
    area: 12400,
    floorsCount: 7,
    buildingType: 'Data Facility & Incubation',
    ulpin: 'BASE-V01-B02-CX',
    position: [26, 0, -6],
    dimensions: [14, 32, 14],
    status: 'ACTIVE',
  },
  {
    id: 'bldg-03',
    parcelId: 'parcel-kp2-0442',
    name: 'Bhaskara Civic Infrastructure (Building 03)',
    code: 'BUILDING 03',
    height: 22,
    area: 7600,
    floorsCount: 4,
    buildingType: 'Utility & Command Facility',
    ulpin: 'BASE-V01-B03-CX',
    position: [-24, 0, 8],
    dimensions: [12, 22, 12],
    status: 'ACTIVE',
  },
  {
    id: 'bldg-04',
    parcelId: 'parcel-gift-0901',
    name: 'Fintech Tower Alpha',
    code: 'BUILDING 01',
    height: 72,
    area: 34000,
    floorsCount: 16,
    buildingType: 'Banking & Financial Hub',
    ulpin: 'BASE-V02-B01-CX',
    position: [0, 0, 0],
    dimensions: [20, 72, 18],
    status: 'ACTIVE',
  },
];

export const INITIAL_FLOORS: Floor[] = [
  {
    id: 'floor-b2',
    buildingId: 'bldg-01',
    floorNumber: -2,
    floorLabel: 'B2',
    heightOffset: -6,
    area: 1650,
    flatsCount: 4,
    status: 'VERIFIED',
    ulpin: 'BASE-VB2-FLB2-CX',
  },
  {
    id: 'floor-b1',
    buildingId: 'bldg-01',
    floorNumber: -1,
    floorLabel: 'B1',
    heightOffset: -3,
    area: 1650,
    flatsCount: 4,
    status: 'VERIFIED',
    ulpin: 'BASE-VB1-FLB1-CX',
  },
  {
    id: 'floor-g',
    buildingId: 'bldg-01',
    floorNumber: 0,
    floorLabel: 'G',
    heightOffset: 0,
    area: 1720,
    flatsCount: 4,
    status: 'VERIFIED',
    ulpin: 'BASE-V00-FL00-CX',
  },
  {
    id: 'floor-1',
    buildingId: 'bldg-01',
    floorNumber: 1,
    floorLabel: '1',
    heightOffset: 4.8,
    area: 1680,
    flatsCount: 6,
    status: 'VERIFIED',
    ulpin: 'BASE-V01-FL01-CX',
  },
  {
    id: 'floor-2',
    buildingId: 'bldg-01',
    floorNumber: 2,
    floorLabel: '2',
    heightOffset: 9.6,
    area: 1680,
    flatsCount: 6,
    status: 'VERIFIED',
    ulpin: 'BASE-V02-FL02-CX',
  },
  {
    id: 'floor-3',
    buildingId: 'bldg-01',
    floorNumber: 3,
    floorLabel: '3',
    heightOffset: 14.4,
    area: 1680,
    flatsCount: 6,
    status: 'VERIFIED',
    ulpin: 'BASE-V03-FL03-CX',
  },
  {
    id: 'floor-4',
    buildingId: 'bldg-01',
    floorNumber: 4,
    floorLabel: '4',
    heightOffset: 19.2,
    area: 1680,
    flatsCount: 6,
    status: 'VERIFIED',
    ulpin: 'BASE-V04-FL04-CX',
  },
  {
    id: 'floor-5',
    buildingId: 'bldg-01',
    floorNumber: 5,
    floorLabel: '5',
    heightOffset: 24.0,
    area: 1680,
    flatsCount: 6,
    status: 'VERIFIED',
    ulpin: 'BASE-V05-FL05-CX',
  },
  {
    id: 'floor-6',
    buildingId: 'bldg-01',
    floorNumber: 6,
    floorLabel: '6',
    heightOffset: 28.8,
    area: 1680,
    flatsCount: 6,
    status: 'VERIFIED',
    ulpin: 'BASE-V06-FL06-CX',
  },
  {
    id: 'floor-7',
    buildingId: 'bldg-01',
    floorNumber: 7,
    floorLabel: '7',
    heightOffset: 33.6,
    area: 1680,
    flatsCount: 6,
    status: 'VERIFIED',
    ulpin: 'BASE-V07-FL07-CX',
  },
  {
    id: 'floor-8',
    buildingId: 'bldg-01',
    floorNumber: 8,
    floorLabel: '8',
    heightOffset: 38.4,
    area: 1680,
    flatsCount: 4,
    status: 'VERIFIED',
    ulpin: 'BASE-V08-FL08-CX',
  },
];

export const INITIAL_FLATS: Flat[] = [
  {
    id: 'flat-0701',
    floorId: 'floor-7',
    buildingId: 'bldg-01',
    flatNumber: 'Flat 0701',
    area: 195,
    type: 'Commercial Office Suite',
    ulpin: 'BASE-V07-U0701-CX',
    ownerStatus: 'Registered Deed #4401',
    status: 'CLEAR',
    positionIndex: 0,
  },
  {
    id: 'flat-0702',
    floorId: 'floor-7',
    buildingId: 'bldg-01',
    flatNumber: 'Flat 0702',
    area: 210,
    type: 'Technology Innovation Lab',
    ulpin: 'BASE-V07-U0702-CX',
    ownerStatus: 'Registered Deed #4402',
    status: 'CLEAR',
    positionIndex: 1,
  },
  {
    id: 'flat-0703',
    floorId: 'floor-7',
    buildingId: 'bldg-01',
    flatNumber: 'Flat 0703',
    area: 180,
    type: 'R&D Executive Suite',
    ulpin: 'BASE-V07-U0703-CX',
    ownerStatus: 'Registered Deed #4403',
    status: 'CLEAR',
    positionIndex: 2,
  },
  {
    id: 'flat-0704',
    floorId: 'floor-7',
    buildingId: 'bldg-01',
    flatNumber: 'Flat 0704',
    area: 185,
    type: 'Cadastral Intelligence Studio',
    ulpin: 'BASE-V07-U0704-CX',
    ownerStatus: 'Registered Deed #4404',
    status: 'CLEAR',
    positionIndex: 3,
  },
  {
    id: 'flat-0705',
    floorId: 'floor-7',
    buildingId: 'bldg-01',
    flatNumber: 'Flat 0705',
    area: 160,
    type: 'Precision Geospatial Lab',
    ulpin: 'BASE-V07-U0705-CX',
    ownerStatus: 'Allotted',
    status: 'MUTATION_IN_PROGRESS',
    positionIndex: 4,
  },
  {
    id: 'flat-0706',
    floorId: 'floor-7',
    buildingId: 'bldg-01',
    flatNumber: 'Flat 0706',
    area: 220,
    type: 'Executive Boardroom & Terrace',
    ulpin: 'BASE-V07-U0706-CX',
    ownerStatus: 'Registered Deed #4406',
    status: 'CLEAR',
    positionIndex: 5,
  },
];

export const MOCK_DIGILOCKER_MAP: Record<string, DigiLockerIntegration> = {
  'BASE-V07-U0704-CX': {
    isMock: true,
    label: 'DEMO INTEGRATION',
    status: 'VERIFIED',
    documentId: 'DL-IND-CADASTRAL-2026-0704',
    deedType: '3D Cadastral Spatial Title Deed (Standard Form 14)',
    issueDate: '2026-01-18',
    signatory: 'Sub-Registrar Gautam Buddha Nagar, Uttar Pradesh',
    verificationHash: 'SHA256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
  },
};

export const MOCK_BANK_KYC_MAP: Record<string, BankKycIntegration> = {
  'BASE-V07-U0704-CX': {
    isMock: true,
    label: 'DEMO INTEGRATION',
    status: 'CLEAR',
    lendingInstitution: 'State Bank of India — Commercial Asset Branch',
    mortgageStatus: 'Zero Encumbrance / Title Clean Certificate issued',
    loanAccountRef: 'SBI-CORP-KP2-99812-NIL',
    lastUpdated: '2026-03-01',
  },
};

export const INITIAL_SURVEY_RECORDS: SurveyRecord[] = [
  {
    id: 'surv-rec-01',
    buildingId: 'bldg-01',
    buildingName: 'Aryabhata Innovation Tower (Building 01)',
    parcelId: 'parcel-kp2-0442',
    parcelName: 'Knowledge Park II — Institutional Sector 3',
    location: 'Knowledge Park II, Greater Noida, Gautam Buddha Nagar, Uttar Pradesh',
    coordinates: { lat: 28.4682, lng: 77.5042 },
    surveyDate: '2026-03-14',
    surveyorId: 'usr-surv-01',
    surveyorName: 'Chief Cadastral Surveyor (Officer #704)',
    ulpin3D: 'BASE-V01-B01-CX',
    heightMeters: 48.0,
    floorsCount: 10,
    areaSqM: 18200,
    methodology: 'Drone Photogrammetry',
    status: 'APPROVED',
    complianceScore: 98,
    notes: 'LiDAR point cloud perfectly matches sanctioned FAR & setback clearance. 3D volumetric boundary locked in National Cadastral Repository.',
    inspectionRef: 'SURV/2026/UP-GNB/0891',
  },
  {
    id: 'surv-rec-02',
    buildingId: 'bldg-02',
    buildingName: 'Brahmagupta Computing Wing (Building 02)',
    parcelId: 'parcel-kp2-0442',
    parcelName: 'Knowledge Park II — Institutional Sector 3',
    location: 'Knowledge Park II, Greater Noida, Gautam Buddha Nagar, Uttar Pradesh',
    coordinates: { lat: 28.4685, lng: 77.5046 },
    surveyDate: '2026-03-12',
    surveyorId: 'usr-surv-01',
    surveyorName: 'Chief Cadastral Surveyor (Officer #704)',
    ulpin3D: 'BASE-V01-B02-CX',
    heightMeters: 32.0,
    floorsCount: 7,
    areaSqM: 12400,
    methodology: 'Terrestrial LiDAR',
    status: 'APPROVED',
    complianceScore: 96,
    notes: '7 floors verified along Z-axis. Rooftop antenna installation within permitted height envelope.',
    inspectionRef: 'SURV/2026/UP-GNB/0874',
  },
  {
    id: 'surv-rec-03',
    buildingId: 'bldg-03',
    buildingName: 'Bhaskara Civic Infrastructure (Building 03)',
    parcelId: 'parcel-kp2-0442',
    parcelName: 'Knowledge Park II — Institutional Sector 3',
    location: 'Knowledge Park II, Greater Noida, Gautam Buddha Nagar, Uttar Pradesh',
    coordinates: { lat: 28.4678, lng: 77.5038 },
    surveyDate: '2026-03-05',
    surveyorId: 'usr-surv-01',
    surveyorName: 'Chief Cadastral Surveyor (Officer #704)',
    ulpin3D: 'BASE-V01-B03-CX',
    heightMeters: 22.0,
    floorsCount: 4,
    areaSqM: 7600,
    methodology: 'RTK GNSS + Laser',
    status: 'APPROVED',
    complianceScore: 94,
    notes: 'Utility substation and primary command facility boundary verified. Transformer setback complies with fire safety grid.',
    inspectionRef: 'SURV/2026/UP-GNB/0852',
  },
  {
    id: 'surv-rec-04',
    buildingId: 'bldg-04',
    buildingName: 'Fintech Tower Alpha',
    parcelId: 'parcel-gift-0901',
    parcelName: 'GIFT City DTA Commercial Zone — Block C',
    location: 'GIFT City Block C, Gandhinagar, Gujarat',
    coordinates: { lat: 23.1610, lng: 72.6841 },
    surveyDate: '2026-02-27',
    surveyorId: 'usr-surv-01',
    surveyorName: 'Chief Cadastral Surveyor (Officer #704)',
    ulpin3D: 'BASE-V02-B01-CX',
    heightMeters: 72.0,
    floorsCount: 16,
    areaSqM: 34000,
    methodology: 'Drone Photogrammetry',
    status: 'APPROVED',
    complianceScore: 99,
    notes: 'Dual GNSS baseline calibration. 16 floors scanned with terrestrial point density 400 pts/m². Certified for IFSC registry.',
    inspectionRef: 'SURV/2026/GJ-GND/0411',
  },
  {
    id: 'surv-rec-05',
    buildingId: 'bldg-05',
    buildingName: 'Silicon Vista Technopark — Block A',
    parcelId: 'parcel-ecity-108',
    parcelName: 'Electronic City Phase 1 — Sub-division 12',
    location: 'Hosur Road, Electronic City Phase 1, Bengaluru Urban, Karnataka',
    coordinates: { lat: 12.8452, lng: 77.6602 },
    surveyDate: '2026-02-18',
    surveyorId: 'usr-surv-01',
    surveyorName: 'Chief Cadastral Surveyor (Officer #704)',
    ulpin3D: 'KA-BLR-B01-3DULPIN-9120',
    heightMeters: 54.0,
    floorsCount: 12,
    areaSqM: 28600,
    methodology: 'Total Station & Satellite',
    status: 'APPROVED',
    complianceScore: 95,
    notes: 'Subdivided IT parcel boundary demarcation completed. Baseline survey coordinates cross-checked with Survey of India benchmark.',
    inspectionRef: 'SURV/2026/KA-BLR/1029',
  },
  {
    id: 'surv-rec-06',
    buildingId: 'bldg-06',
    buildingName: 'Cyber Heights Tower B',
    parcelId: 'parcel-cyb-0412',
    parcelName: 'Cyber City Sector 25A — Parcel 412',
    location: 'Sector 25A, DLF Cyber City, Gurugram, Haryana',
    coordinates: { lat: 28.4950, lng: 77.0892 },
    surveyDate: '2026-02-10',
    surveyorId: 'usr-surv-01',
    surveyorName: 'Chief Cadastral Surveyor (Officer #704)',
    ulpin3D: 'HR-GGN-B02-3DULPIN-4122',
    heightMeters: 62.0,
    floorsCount: 14,
    areaSqM: 31200,
    methodology: 'Terrestrial LiDAR',
    status: 'FLAGGED_DISCREPANCY',
    complianceScore: 82,
    notes: 'Flagged for setback discrepancy on eastern easement: 1.8m deviation from sanction blueprint on floor 11 cantilever.',
    inspectionRef: 'SURV/2026/HR-GGN/0315',
  },
  {
    id: 'surv-rec-07',
    buildingId: 'bldg-07',
    buildingName: 'Vedic Biotech Nexus (Building 04)',
    parcelId: 'parcel-kp2-0442',
    parcelName: 'Knowledge Park II — Institutional Sector 3',
    location: 'Plot 18, Knowledge Park II, Greater Noida, Uttar Pradesh',
    coordinates: { lat: 28.4691, lng: 77.5055 },
    surveyDate: '2026-01-29',
    surveyorId: 'usr-surv-01',
    surveyorName: 'Chief Cadastral Surveyor (Officer #704)',
    ulpin3D: 'UP-GNB-B04-3DULPIN-1890',
    heightMeters: 38.0,
    floorsCount: 8,
    areaSqM: 15400,
    methodology: 'RTK GNSS + Laser',
    status: 'APPROVED',
    complianceScore: 97,
    notes: 'Green laboratory building certified. Spatial volumetric coordinates authenticated for environmental clearance.',
    inspectionRef: 'SURV/2026/UP-GNB/0721',
  },
  {
    id: 'surv-rec-08',
    buildingId: 'bldg-08',
    buildingName: 'Narmada Riverfront Trade Pavilion',
    parcelId: 'parcel-gift-0901',
    parcelName: 'GIFT City DTA Commercial Zone — Block C',
    location: 'SEZ Riverfront Corridor, GIFT City, Gandhinagar, Gujarat',
    coordinates: { lat: 23.1635, lng: 72.6862 },
    surveyDate: '2026-01-15',
    surveyorId: 'usr-surv-01',
    surveyorName: 'Chief Cadastral Surveyor (Officer #704)',
    ulpin3D: 'GJ-GND-B02-3DULPIN-5541',
    heightMeters: 42.0,
    floorsCount: 9,
    areaSqM: 19800,
    methodology: 'Drone Photogrammetry',
    status: 'APPROVED',
    complianceScore: 99,
    notes: 'Waterfront setback compliance verified against master development plan. Zero overlap on municipal buffer.',
    inspectionRef: 'SURV/2026/GJ-GND/0388',
  },
];

